---
title: "NJIT_PitcherDashboard"
author: "Jack Sylvia"
date: "2024-09-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This will be the initial setup for the shinyApp involving pitching reports following bullpens and live outings for NJIT pitchers. 

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
library(shiny)
```

```{r}
# ui
{ui <- fluidPage(
    
    titlePanel("Highlander Pitching Dashboard"),
    br(),
    sidebarLayout(
      sidebarPanel(
        selectInput(inputId = "pitcherInput", 
                    label = "Select Pitcher",
                    choices = c(sort(unique(clean_data$pitcher_id)))),
        dateRangeInput(inputId = "dateRangeInput",
                       label = "Select Date Range",
                       start = min(clean_data$Date),
                       end = max(clean_data$Date)),
        img(src = "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/NJIT_Highlanders_logo.svg/1200px-NJIT_Highlanders_logo.svg.png", 
            style = "display: block; margin-left: auto; margin-right: auto;",
            height = 150, width = 150)),
      mainPanel(
        ## Design panel setup once actual Trackman data from practice comes in
        )
      )
)
}
```

